# Generated by Django 3.2.9 on 2021-11-24 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateField(auto_now_add=True)),
                ('delais', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('priorite', models.CharField(choices=[('1', 'basse'), ('2', 'moyenne'), ('3', 'elevee')], default='basse', max_length=7)),
                ('duree_estimee', models.IntegerField()),
                ('jour', models.DateField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('etat', models.CharField(max_length=200)),
                ('fichier', models.FileField(null=True, upload_to='')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Suivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorisations', models.BooleanField(default=False)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('1', 'depend de'), ('2', 'recquise pour'), ('3', 'avant'), ('4', 'apres'), ('5', 'en relation')], max_length=13, null=True)),
                ('tache1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='core.tache')),
                ('tache2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tache')),
            ],
        ),
        migrations.CreateModel(
            name='rapport_employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateField()),
                ('time', models.TimeField()),
                ('type_activite', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employe')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='employe',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tache'),
        ),
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.user'),
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('fichier', models.FileField(null=True, upload_to='')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
        ),
    ]
