# Generated by Django 3.2.9 on 2021-11-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='etat',
            field=models.CharField(default='en cours', max_length=200),
        ),
        migrations.AddField(
            model_name='tache',
            name='unite_duree',
            field=models.CharField(choices=[('1', 'seconde'), ('2', 'min'), ('3', 'heure'), ('4', 'jour'), ('5', 'semaine'), ('6', 'mois'), ('7', 'annee')], default='min', max_length=7),
        ),
    ]
