# Generated by Django 3.2.9 on 2021-11-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211124_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='unite_delais',
            field=models.CharField(choices=[('1', 'seconde'), ('2', 'min'), ('3', 'heure'), ('4', 'jour'), ('5', 'semaine'), ('6', 'mois'), ('7', 'annee')], default='jour', max_length=7),
        ),
        migrations.AlterField(
            model_name='tache',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='jour',
            field=models.DateField(default=None, null=True),
        ),
    ]
