# Generated by Django 3.2.9 on 2021-11-24 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211124_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport_employe',
            old_name='date_joined',
            new_name='date_choisie',
        ),
        migrations.RenameField(
            model_name='rapport_employe',
            old_name='time',
            new_name='temps_choisi',
        ),
        migrations.AddField(
            model_name='commentaires',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
