# Generated by Django 3.2.9 on 2021-11-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_relation_user_suivre_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projet'),
        ),
    ]
