# Generated by Django 3.2.9 on 2021-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tache_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='etat',
            field=models.CharField(choices=[('termine', 'termine'), ('en cours', 'en cours')], default='en cours', max_length=200),
        ),
    ]
