# Generated by Django 3.2.9 on 2022-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tache_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='unite_delais',
            field=models.CharField(choices=[('secondes', 'secondes'), ('mins', 'mins'), ('heures', 'heures'), ('jours', 'jours'), ('semaines', 'semaines'), ('mois', 'mois'), ('annees', 'annees')], default='jour', max_length=8),
        ),
        migrations.AlterField(
            model_name='tache',
            name='duree_estimee',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='tache',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tache',
            name='jour',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('basse', 'basse'), ('moyenne', 'moyenne'), ('elevee', 'elevee')], default='basse', max_length=7),
        ),
        migrations.AlterField(
            model_name='tache',
            name='unite_duree',
            field=models.CharField(choices=[('secondes', 'secondes'), ('mins', 'mins'), ('heures', 'heures'), ('jours', 'jours'), ('semaines', 'semaines'), ('mois', 'mois'), ('annees', 'annees')], default='mins', max_length=8),
        ),
    ]
