# Generated by Django 3.2.9 on 2022-01-13 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220104_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='unite_duree',
        ),
    ]
