# Generated by Django 3.2.9 on 2022-02-12 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_remove_tache_unite_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='user_asign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='etat',
            field=models.CharField(choices=[('termine', 'termine'), ('en cours', 'en cours'), ('nouveau', 'nouveau'), ('investigation', 'investigation'), ('besoin de clarification', 'besoin de clarification'), ('estimation de temps', 'estimation de temps'), ('pres pour commencer', 'pres pour commencer'), ('en test', 'en test'), ('deployer', 'deployer'), ('completer', 'completer'), ('duplicate/double/repetition', 'duplicate/double/repetition'), ('fermer', 'fermer'), ('enquete a revoir/ pas sure de la cause', 'enquete a revoir/ pas sure de la cause')], default='en cours', max_length=200),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('basse', 'basse'), ('moyenne', 'moyenne'), ('elevee', 'elevee'), ('critical/absolute', 'critical/absolute')], default='basse', max_length=17),
        ),
        migrations.AlterField(
            model_name='tache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
